spring.application.name=mycoolapp

# testprops
# custom properties
my.name=Irsyad

# configure server port
server.port=8484

# actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# exclude endpoints exposed
# management.endpoints.web.exposure.exclude=health,info

# info app
info.app.name=My super cool app
info.app.description=siren song
info.app.version=1.0.0

# super user for securing endpoints
spring.security.user.name=icad
spring.security.user.password=12345

# Set the context path of the application
server.servlet.context-path=/mycoolapp