spring.application.name=mycoolapp

# testprops
my.name=Irsyad

# configure server port
server.port=8484

# actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# info app
info.app.name=My super cool app
info.app.description=siren song
info.app.version=1.0.0
