spring.application.name=mycoolapp

# testprops
# custom properties
my.name=Irsyad

# configure server port
server.port=8484

# actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# exclude endpoints exposed
# management.endpoints.web.exposure.exclude=health,info

# info app
info.app.name=My super cool app
info.app.description=siren song
info.app.version=1.0.0

# super user for securing endpoints
spring.security.user.name=icad
spring.security.user.password=12345

# Set the context path of the application
# make it localhost:xxxx/mycoolapp/{some url}
# server.servlet.context-path=/mycoolapp

# Lazy Initialization
# spring.main.lazy-initialization=true

# Connect Database
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Turn off Spring Boot Banner in terminal
spring.main.banner-mode=off

# Reduce logging level. Set to Warn
logging.level.root=warn